[package]
name = "geometry_project1"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]

[dependencies]
cgmath = "0.7.0"
glium = "0.13.5"
hyper = "0.7.2"
# nalgebra = "0.8.2"
rand = "0.3.14"
serde_json = "0.7.0"
